### ISSUE TITLE
CPV stops when View is reused

### ISSUE THREAD

**Issue by OFmarting** [rahatarmanahmed/CircularProgressView#20]
Commit 8ea4a9d73edc607cbf42a932bc1811bebfc32b58 resolves the memory leak but introduces a minor issue. When using the CPV in a ListView or RecyclerView where Views are recycled/reused the CPV hangs when it gets visible the second time. The solution is to override ```onAttachedToWindow()``` and call ```startAnimation()``` there.

I think you could even move the block

```
if(autostartAnimation)
    startAnimation();
```
from ```init(AttributeSet attrs, int defStyle)``` to ```onAttachedToWindow()```.

**Comment by rahatarmanahmed** [comment]
Just released `v2.3.2` with the fix, should be available in a few hours.
