### ISSUE TITLE
For Ecipse ? 

### ISSUE THREAD

**Issue by aliansari-powerfulpal** [rahatarmanahmed/CircularProgressView#27]
How can I add this in my eclipse project ?

**Comment by rahatarmanahmed** [comment]
If your eclipse android project uses gradle, you can [include it as a dependency](https://github.com/rahatarmanahmed/CircularProgressView#usage) in your gradle build file. I don't really know how to add maven dependencies in Eclipse without gradle, though.

Eclipse's ADT is no longer in active development, the Android Developer Blog suggests you migrate to Android Studio:
http://android-developers.blogspot.com/2015/06/an-update-on-eclipse-android-developer.html
https://developer.android.com/sdk/installing/migrate.html

**Comment by rahatarmanahmed** [comment]
You may be able to clone this repo, build it with `./gradlew build`, and look in the `circularprogressview/build` folder and see if it gives you a .jar or .aar you can use.
