### ISSUE TITLE
Circle Background Color ?

### ISSUE THREAD

**Issue by robertoestivill** [rahatarmanahmed/CircularProgressView#29]
Any way of setting the "behind progress color" like in [this example] (https://github.com/robertoestivill/CircularProgressBar) ?

![background color] (https://camo.githubusercontent.com/b307776374be949ad6c9d6bccd238c36ad876619/687474703a2f2f63646e2e6d616b65616769662e636f6d2f6d656469612f31302d32302d323031352f5a75534f73512e676966 "background color")

**Comment by rahatarmanahmed** [comment]
CPV doesn't have any support for this but I don't imagine it'd be too tough to
draw a circle drawable with the background you want and stack the CPV on top
of it.

> On Dec 9 2015, at 7:00 am, Robert &lt;notifications@github.com&gt; wrote:  

>

> Any way of setting the "behind progress color" like in [this
example](https://github.com/robertoestivill/CircularProgressBar) ?

>

> [![background color](https://camo.githubusercontent.com/b307776374be949ad6c9
d6bccd238c36ad876619/687474703a2f2f63646e2e6d616b65616769662e636f6d2f6d6564696
12f31302d32302d323031352f5a75534f73512e676966)](https://camo.githubusercontent
.com/b307776374be949ad6c9d6bccd238c36ad876619/687474703a2f2f63646e2e6d616b6561
6769662e636f6d2f6d656469612f31302d32302d323031352f5a75534f73512e676966)

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/rahatar
manahmed/CircularProgressView/issues/29).![](https://github.com/notifications/
beacon/ADBudtgkU-_RBbv115eOsirwop1ngbxZks5pODmdgaJpZM4Gx674.gif)
