### ISSUE TITLE
i am geerting crash on android 4.4 because of com.github.rahatarmanahmed.cpv.CircularProgressView

### ISSUE THREAD

**Issue by neerajkrshah** [rahatarmanahmed/CircularProgressView#30]
i am getting crash on android 4.4 & 4.1 (Kitkat )only because of com.github.rahatarmanahmed.cpv.CircularProgressView except Android 4.4 it is working fine.

See attached images Please tell me what is the solution for same ?

![s](https://cloud.githubusercontent.com/assets/7594182/12383599/eb6454d4-bdcd-11e5-9dbe-ba18c363a36d.PNG)

**Comment by rahatarmanahmed** [comment]
This doesn't seem to be an issue with CPV, but with your project not generating the R$styleable class correctly. Lots of answers can be found googling for `NoClassDefFoundError Styleable`.
