### ISSUE TITLE
Finishing Animation for Indertiminate progress

### ISSUE THREAD

**Issue by abhiank209** [rahatarmanahmed/CircularProgressView#31]
Hey, 

Thankx for this library. I just have one request. Could you please add a method to finish the animation for indeterminate progress?

Simply hiding the progress bar suddenly when the background task is complete looks janky and I would love for the animation to complete the full circle before dissapearing. Please add that if its not too much work..

Thankx

**Comment by rahatarmanahmed** [comment]
Glad to see this library is helpful to you. Unfortunately, I am no longer actively maintaining this library.

On top of that, I don't think the official Material indeterminate loader has a finishing animation, so I would be hesitant to deviate from that. (I haven't done any android dev in a while so correct me if I'm wrong)

**Comment by abhiank209** [comment]
Oh, thats too bad.. 
Thankx anyways for making this library. I've created a work-around for now by making the progress bar fade out instead of simply hiding it so its not looking that janky now. 

I'm not sure whether the official design of the circular progress bar has a finishing animation or not, but I saw that a finishing animation in a horizontal bar from another library was looking really nice, so I thought it would look good on this as well.

**Comment by jamesddube** [comment]
Had the same issue when i started... I used it for my final year project. You can refer to the response here
[https://github.com/rahatarmanahmed/CircularProgressView/issues/6](url)

**Comment by smalichenko** [comment]
For anyone who's still have the same issue – i've found an easy workaround. Just place two CircularProgressViews. Determinate view over the indeterminate view. Also add a listener for determinate one:

`            determinateProgressBar.addListener(new CircularProgressViewAdapter() {
                @Override
                public void onProgressUpdateEnd(final float currentProgress) {
                    if (currentProgress == 100f) {
                        success = true;
                        indeterminateProgressBar.setVisibility(View.GONE);
                        successView.setVisibility(View.VISIBLE);
                        titleView.setText(R.string.success);
                        actionButton.setBackgroundResource(R.drawable.shape_publication_btn_enabled);
                        actionButton.setTextColor(getResources().getColor(R.color.white));
                        actionButton.setText(R.string.create_more);
                    }
                }`

And that's it :)
