### ISSUE TITLE
Webview

### ISSUE THREAD

**Issue by arpit999bicubic** [rahatarmanahmed/CircularProgressView#35]
not showing in **webview** please fix this.

**Comment by rahatarmanahmed** [comment]
uh, why would it show up in a webview?

**Comment by arpit999bicubic** [comment]
Because i wanna to load webpage in fragment.

**Comment by rahatarmanahmed** [comment]
This widget isn't going to show up in a webview, though. You have to manually control it. Try something like this but with CPV instead: http://stackoverflow.com/questions/2537454/android-webview-progress-bar

**Comment by arpit999bicubic** [comment]
Okay sir thanks one more question it is not showing in activity also can
you help me

**Comment by rahatarmanahmed** [comment]
If you can post a minimal reproduction of the issue, yes.

**Comment by arpit999bicubic** [comment]
Please check my java and xml file it not work in login.

**Comment by rahatarmanahmed** [comment]
You didn't post your code.

On Jul 18, 2016 12:27 AM, "arpit999bicubic" <notifications@github.com>
wrote:
>
> Please check my java and xml file it not work in login.
>
> On Mon, Jul 18, 2016 at 7:42 AM, Rahat Ahmed <notifications@github.com>
> wrote:
>
> > If you can post a minimal reproduction of the issue, yes.
> >
> > —
> > You are receiving this because you authored the thread.
>
> > Reply to this email directly, view it on GitHub
> > <
https://github.com/rahatarmanahmed/CircularProgressView/issues/35#issuecomment-233218263
