### ISSUE TITLE
Unable to change the size

### ISSUE THREAD

**Issue by Ajk2rxKamehameha** [rahatarmanahmed/CircularProgressView#39]
I want a smaller progress view but I am not able to change the size.

**Comment by rahatarmanahmed** [comment]
CircularProgressView can be sized like any other android View. This is
likely an issue with your layout.

If you can provide a reproducible example specific to CPV then we can
reopen this issue but meanwhile you can get help from any other Android
community like StackOverflow.

**Comment by Ajk2rxKamehameha** [comment]
@rahatarmanahmed rahatarmanahmed It's working Amazingly, thanks. I did some mistake in layout params.
