### ISSUE TITLE
Long animation leaves 4 colored places at 0, 90, 180 and 270 angles

### ISSUE THREAD

**Issue by priceinjector** [rahatarmanahmed/CircularProgressView#4]
Thank you for the great widget! One small issue:
On android 4.4.2, While the circle is animated for more than 5 cycles it starts painting the 4 places. These are the points where the bound box touches the circle.
If I set the Paint to be aliased then it doesn't happen.
![progress_issue](https://cloud.githubusercontent.com/assets/11571147/6765109/78a980c2-cfda-11e4-82bf-be72bee7d9dd.png)

**Comment by rahatarmanahmed** [comment]
Have you confirmed this on a real device? I had this issue but wasn't able
to duplicate it outside of the emulator.

**Comment by priceinjector** [comment]
Yes, this image from samsung galaxy s4 with 4.4.2

**Comment by rahatarmanahmed** [comment]
Alright, can you send a PR with the fix, then?

**Comment by priceinjector** [comment]
The fix is just a workaround...I have removed the anti aliased flag on the Paint() constructor

**Comment by rahatarmanahmed** [comment]
Oh you *removed* the flag. Okay let me look into it.

**Comment by priceinjector** [comment]
It looks less smooth when looking very close to it however :)

**Comment by rahatarmanahmed** [comment]
@priceinjector can you test this change to confirm it fixes the issue? It makes the arc smaller so it doesn't paint outside its bounds, which I believe is why it doesn't repaint those marks.

**Comment by priceinjector** [comment]
Works like a charm! Thank you
