### ISSUE TITLE
NPE in CircularProgressView

### ISSUE THREAD

**Issue by siga111** [rahatarmanahmed/CircularProgressView#5]
Hi! 

Two random crashes showed up in Crashlytics. Not sure in what circumstances and how to reproduce it. Never encountered myself. Just for your information, maybe there is something obviuos.

Devices: Sony ST26I (4.1.2) and LG-E460 (4.1.2)

```
java.lang.NullPointerException
       at android.view.GLES20Canvas.drawArc(GLES20Canvas.java:726)
       at com.github.rahatarmanahmed.cpv.CircularProgressView.onDraw(CircularProgressView.java:119)
       at android.view.View.draw(View.java:13573)
       at android.view.View.getDisplayList(View.java:12524)
       at android.view.View.getDisplayList(View.java:12568)
       at android.view.View.draw(View.java:13297)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3037)
...
```

Thanks for awesome library.

**Comment by rahatarmanahmed** [comment]
Which version are you using?

**Comment by siga111** [comment]
1.0.0 in production.

**Comment by rahatarmanahmed** [comment]
Sorry, I don't see an obvious reason why it would drop an NPE like that. Does it happen instantly or maybe after switching into the application?

**Comment by siga111** [comment]
As I stated before, that stacktrace is from Crashlytics, I have never encountered this crash myself. I will investigate a bit and update if I find some new details.

**Comment by siga111** [comment]
I managed to reproduce it. NPE happens when I open and close and close activity with progress view very fast.

**Comment by rahatarmanahmed** [comment]
I made some changes that may prevent the NPE, can you try forking from my
latest commit and seeing if the problem persists?

**Comment by siga111** [comment]
Well, I am not able to reproduce it in test project (It may be different in actual project), so lets assume its fixed and if something shows up, I will make a pull request.

**Comment by rahatarmanahmed** [comment]
Pushed those changes to v2.0.1. Feel free to update your dependency to that
tomorrow. For now, I will close this issue.

On Fri, Mar 27, 2015 at 2:57 PM, Sergejs Luhmirins <notifications@github.com
