### ISSUE TITLE
Stoping the animation

### ISSUE THREAD

**Issue by sweadklever** [rahatarmanahmed/CircularProgressView#6]
Hie  Guys

Im grateful for your piece of work, but however i have an issue. The thing is, everything works fine, when im doing an async task the progressview should animate ( and it does,using the method startAnimation() ) but my challenge comes to when i want to stop the animation...i would suggest for a stopAnimation() method...thanks again

**Comment by rahatarmanahmed** [comment]
How exactly do you want the animation to stop? If you want it to just disappear, it's easier to set the visibility on the view to false.

**Comment by sweadklever** [comment]
sorry for late response, i just followed your advice and it works.....thanks
